[phases.setup]
nixPkgs = [
  "python312",

  # Toolchain C
  "gcc",
  "binutils",
  "pkg-config",

  # Cairo stack (IMPORTANTE: .dev)
  "cairo.dev",
  "pango.dev",
  "gdk-pixbuf",
  "glib",
  "libffi",

  # Build tools
  "cmake",
  "meson",
  "ninja"
]
