[phases.setup]
nixPkgs = [
  "python312",

  # Toolchain C (OBLIGATORIO para pycairo)
  "gcc",
  "binutils",
  "pkg-config",

  # Cairo / PDF stack
  "cairo",
  "pango",
  "gdk-pixbuf",
  "glib",
  "libffi",

  # Build tools usados por pycairo
  "cmake",
  "meson",
  "ninja"
]
