[phases.setup]
nixPkgs = [
  "python312",

  # Toolchain
  "gcc",
  "binutils",
  "pkg-config",

  # Cairo (AMBOS)
  "cairo",
  "cairo.dev",

  # Dependencias relacionadas
  "glib",
  "glib.dev",
  "pango",
  "pango.dev",
  "gdk-pixbuf",

  # Build tools
  "cmake",
  "meson",
  "ninja"
]
[env]
PKG_CONFIG_PATH = "/root/.nix-profile/lib/pkgconfig"
